create extension if not exists pgcrypto;

create table if not exists insurance_policies (
  id bigint generated by default as identity primary key,
  provider_name varchar not null,
  tier varchar not null,
  deductible numeric default 0,
  max_out_of_pocket numeric default 0
);

create index if not exists insurance_policies_tier_idx
  on insurance_policies (tier);

create table if not exists specialties (
  id bigint generated by default as identity primary key,
  name varchar not null,
  base_consultation_cost numeric not null default 0
);

create table if not exists hospitals (
  id bigint generated by default as identity primary key,
  name varchar not null,
  address text,
  lat numeric,
  lon numeric,
  accepted_tiers text[] not null default '{}'::text[],
  price_multiplier numeric not null default 1.0
);

create table if not exists coverages (
  id bigint generated by default as identity primary key,
  policy_id bigint references insurance_policies(id) on delete cascade,
  specialty_id bigint references specialties(id) on delete cascade,
  coverage_percentage numeric not null,
  flat_copay numeric default 0,
  visit_type varchar default 'ROUTINE'
);

create unique index if not exists coverages_policy_specialty_visit_idx
  on coverages (policy_id, specialty_id, visit_type);

create table if not exists hospital_insurance_contracts (
  id bigint generated by default as identity primary key,
  hospital_id bigint references hospitals(id) on delete cascade,
  policy_id bigint references insurance_policies(id) on delete cascade,
  network_status varchar default 'in_network',
  negotiated_discount numeric default 0,
  created_at timestamptz not null default now()
);

create index if not exists hospital_insurance_contracts_policy_idx
  on hospital_insurance_contracts (policy_id);

create index if not exists hospital_insurance_contracts_hospital_idx
  on hospital_insurance_contracts (hospital_id);

create table if not exists users (
  id bigint generated by default as identity primary key,
  name varchar,
  email varchar,
  location_lat numeric,
  location_lon numeric,
  policy_id bigint references insurance_policies(id),
  ytd_deductible_spent numeric default 0,
  ytd_oop_spent numeric default 0
);

create table if not exists consultation_history (
  id bigint generated by default as identity primary key,
  user_id bigint references users(id),
  symptoms text,
  suggested_specialty varchar,
  urgency_level int,
  created_at timestamptz not null default now()
);

create table if not exists copay_estimations (
  id bigint generated by default as identity primary key,
  consultation_history_id bigint references consultation_history(id) on delete cascade,
  hospital_id bigint references hospitals(id) on delete cascade,
  base_cost numeric,
  negotiated_cost numeric,
  estimated_insurance_coverage numeric,
  estimated_patient_responsibility numeric,
  is_deductible_applied boolean default false,
  agent_reasoning jsonb,
  created_at timestamptz not null default now()
);

create table if not exists chat_history (
  id uuid primary key default gen_random_uuid(),
  session_id text not null,
  role text not null,
  content text not null,
  created_at timestamptz not null default now()
);

create index if not exists chat_history_session_idx
  on chat_history (session_id, created_at);

create table if not exists hospital_recommendations (
  id uuid primary key default gen_random_uuid(),
  user_id uuid,
  query text not null,
  hospitals jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists hospital_recommendations_created_at_idx
  on hospital_recommendations (created_at desc);
